version: "3"

services:
    influxdb:
        build: ./influxdbv2
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - $PWD/influxdbv2/data:/var/lib/influxdb2
            - $PWD/influxdbv2/config:/etc/influxdb2
        restart: always
        env_file:
            - .env
        networks:
            - frontend
            - backend
    telegraf:
        build: ./telegraf
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - $PWD/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        networks: 
            - backend
networks:
    frontend:
    backend: